census/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail')
]

ob_census_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^census/', include('census.urls', namespace="census")),
    url(r'^admin/', include(admin.site.urls)),
]

census/models.py
from django.db import models
import json


class APISetting(models.Model):
    api_description = models.CharField(max_length=200)
    api_key = models.CharField(max_length=200)
    api_used = models.CharField(max_length=200, default='false')

    STATES = (
        ('', 'Select a State'),
        ('01', 'Alabama'),
        ('02', 'Alaska'),
        ('04', 'Arizona'),
        ('05', 'Arkansas'),
        ('06', 'California'),
        ('08', 'Colorado'),
        ('09', 'Connecticut'),
        ('10', 'Delaware'),
        ('11', 'Washington, D.C.'),
        ('12', 'Florida'),
        ('13', 'Georgia'),
        ('15', 'Hawaii'),
        ('16', 'Idaho'),
        ('17', 'Illinois'),
        ('18', 'Indiana'),
        ('19', 'Iowa'),
        ('20', 'Kansas'),
        ('21', 'Kentucky'),
        ('22', 'Louisiana'),
        ('23', 'Maine'),
        ('24', 'Maryland'),
        ('25', 'Massachusetts'),
        ('26', 'Michigan'),
        ('27', 'Minnesota'),
        ('28', 'Mississippi'),
        ('29', 'Missouri'),
        ('30', 'Montana'),
        ('31', 'Nebraska'),
        ('32', 'Nevada'),
        ('33', 'New Hampshire'),
        ('34', 'New Jersey'),
        ('35', 'New Mexico'),
        ('36', 'New York'),
        ('37', 'North Carolina'),
        ('38', 'North Dakota'),
        ('39', 'Ohio'),
        ('40', 'Oklahoma'),
        ('41', 'Oregon'),
        ('42', 'Pennsylvania'),
        ('44', 'Rhode Island'),
        ('45', 'South Carolina'),
        ('46', 'South Dakota'),
        ('47', 'Tennessee'),
        ('48', 'Texas'),
        ('49', 'Utah'),
        ('50', 'Vermont'),
        ('51', 'Virginia'),
        ('53', 'Washington'),
        ('54', 'West Virginia'),
        ('55', 'Wisconsin'),
        ('56', 'Wyoming'),
        ('60', 'American Samoa'),
        ('66', 'Guam'),
        ('72', 'Puerto Rico'),
        ('78', 'Virgin Islands'),
    )

    state_selected = models.CharField(max_length=2, choices=STATES, default='')

    def __str__(self):
        return self.api_description


class HousingVariable(models.Model):
    view_housing_variables = models.ForeignKey(APISetting)
    housing_variable = models.CharField(max_length=200)

    def __str__(self):
        return self.housing_variable


class CensusInfo(models.Model):
    census_info = models.CharField(max_length=200)
    api_view_id = models.CharField(max_length=2)

    def census_zip(self):
        census_zip = json.loads(self.census_info)
        return census_zip['zip code tabulation area']

    def __str__(self):
        return self.census_info

census/views.py
from django.views import generic

from .models import APISetting, CensusInfo


class IndexView(generic.ListView):
    template_name = 'census/index.html'
    context_object_name = 'all_census_views'
    # APISetting.objects.exclude(api_used='true')

    def get_queryset(self):
        return APISetting.objects.exclude(api_used='false')


class DetailView(generic.DetailView):
    context_object_name = 'census_view'
    template_name = 'census/detail.html'
    queryset = APISetting.objects.all()

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['censuspoints'] = CensusInfo.objects.all()
        return context

census/templates/census/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    {% load staticfiles %}
    {% load census_extras %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/responsive/1.0.7/js/dataTables.responsive.min.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'census/style.css' %}"/>
    <script src="{% static 'census/census.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/census/">US Cesus Data Views</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/census/">Census Directory</a></li>
                <li><a href="/admin/">Admin Area</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="section-header top">
                <div class="section-header-border">&nbsp;</div>
                <div class="section-header-text"><h2>{{ census_view.api_description }}</h2></div>
            </div>
            <div class="section-header">
                <div class="page_body">
                    <br>
                    <p></p>
                </div>
            </div>

            {% if censuspoints|in_current_view:census_view.id %}
                <table id="census_view" class="display responsive no-wrap" width="100%">
                    <thead>
                    <tr>
                        <th>Zip Code</th>
                        {% for hs_variable_info in census_view.housingvariable_set.all %}

                            <th>{{ hs_variable_info.housing_variable }}</th>

                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for censuspoint in censuspoints %}
                        <tr>
                            <td>{{ censuspoint.census_zip }}</td>
                            {% for hs_variable_info in census_view.housingvariable_set.all %}

                                <td class="{{ hs_variable_info.housing_variable }}">{{ censuspoint.census_info|get_hs_values:hs_variable_info.housing_variable }}</td>

                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
        </div>
    </div>
</div>

</body>
</html>

census/templates/census/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'census/style.css' %}"/>
    <script src="{% static 'census/census.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/census/">US Cesus Data Views</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/census/">Census Directory</a></li>
                <li><a href="/admin/">Admin Area</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="page_header top">
                <h2>Welcome</h2>

                <div class="page_body">
                    <p>This is the Census API admin interface.</p>

                    <p>Here you will see the population and housing in various parts of the country, to help develop
                        stories, check facts, and analyze markets.</p>

                    <p>To see a census view, please add it via the admin area.</p>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="section-header top">
                <div class="section-header-border">&nbsp;</div>
                <div class="section-header-text">Available Views</div>
            </div>
            <div class="row">
                {% if all_census_views %}
                    {% for apisetting in all_census_views %}
                        <div class="col-md-6">
                            <a class="csview_link" href="{% url 'census:detail' apisetting.id %}">
                                <div class="csview_card">
                                    <h4>{{ apisetting.api_description }}</h4>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No census queries are available or have been imported.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

</body>
</html>